
export const unis = [
    {
        id: 1,
        title: 'University of Cape Town',
        img: 'https://cisp.cachefly.net/assets/articles/images/resized/0000980358_resized_uctuppercampuslandscapeview1022.jpg',
        url: 'uct',
        courses: [],
    },
    {
        id: 2,
        title: 'WITS',
        img: 'https://www.wits.ac.za/media/wits-university/study/images/Wits-GreatHall-600x300-credit-Shivan-Parusnath.png',
        url: 'wits',
        courses: [],
    },
    {
        id: 3,
        title: 'University of Pretoria',
        img: 'https://www.thesouthafrican.com/wp-content/uploads/2015/09/Tuks.jpg',
        url: 'tuks',
        courses: [
            
    { 
        year: '2023', 
        title: 'BA', 
        code: '01130015', 
        link: 'https://www.up.ac.za/programmes/programme/01130015/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Audiology', 
        code: '01130105', 
        link: 'https://www.up.ac.za/programmes/programme/01130105/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Fine Arts', 
        code: '01130103', 
        link: 'https://www.up.ac.za/programmes/programme/01130103/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Fine Arts - extended programme', 
        code: '01130107', 
        link: 'https://www.up.ac.za/programmes/programme/01130107/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Information Design', 
        code: '01130102', 
        link: 'https://www.up.ac.za/programmes/programme/01130102/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Languages', 
        code: '01130016', 
        link: 'https://www.up.ac.za/programmes/programme/01130016/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Law', 
        code: '01130086', 
        link: 'https://www.up.ac.za/programmes/programme/01130086/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Speech-Language Pathology', 
        code: '01130104', 
        link: 'https://www.up.ac.za/programmes/programme/01130104/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BA Visual Studies', 
        code: '01130133', 
        link: 'https://www.up.ac.za/programmes/programme/01130133/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BAdmin Public Management and International Relations', 
        code: '07131175', 
        link: 'https://www.up.ac.za/programmes/programme/07131175/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BChD', 
        code: '10136001', 
        link: 'https://www.up.ac.za/programmes/programme/10136001/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCMP', 
        code: '10130012', 
        link: 'https://www.up.ac.za/programmes/programme/10130012/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom', 
        code: '07130222', 
        link: 'https://www.up.ac.za/programmes/programme/07130222/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Accounting Sciences', 
        code: '07130043', 
        link: 'https://www.up.ac.za/programmes/programme/07130043/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Agribusiness Management', 
        code: '07130092', 
        link: 'https://www.up.ac.za/programmes/programme/07130092/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Business Management', 
        code: '07130068', 
        link: 'https://www.up.ac.za/programmes/programme/07130068/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Econometrics', 
        code: '07130012', 
        link: 'https://www.up.ac.za/programmes/programme/07130012/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Economics', 
        code: '07130052', 
        link: 'https://www.up.ac.za/programmes/programme/07130052/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Extended programme', 
        code: '07139923', 
        link: 'https://www.up.ac.za/programmes/programme/07139923/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Financial Sciences', 
        code: '07130206', 
        link: 'https://www.up.ac.za/programmes/programme/07130206/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Human Resource Management', 
        code: '07130144', 
        link: 'https://www.up.ac.za/programmes/programme/07130144/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Informatics Information Systems', 
        code: '07130173', 
        link: 'https://www.up.ac.za/programmes/programme/07130173/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Investment Management', 
        code: '07130205', 
        link: 'https://www.up.ac.za/programmes/programme/07130205/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Law', 
        code: '07130152', 
        link: 'https://www.up.ac.za/programmes/programme/07130152/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Marketing Management', 
        code: '07130162', 
        link: 'https://www.up.ac.za/programmes/programme/07130162/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Statistics and Data Science', 
        code: '07130263', 
        link: 'https://www.up.ac.za/programmes/programme/07130263/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BCom Supply Chain Management', 
        code: '07130067', 
        link: 'https://www.up.ac.za/programmes/programme/07130067/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BConSci Clothing Retail Management', 
        code: '02130110', 
        link: 'https://www.up.ac.za/programmes/programme/02130110/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BConSci Food Retail Management', 
        code: '02130108', 
        link: 'https://www.up.ac.za/programmes/programme/02130108/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BConSci Hospitality Management', 
        code: '02130109', 
        link: 'https://www.up.ac.za/programmes/programme/02130109/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BDietetics', 
        code: '10139003', 
        link: 'https://www.up.ac.za/programmes/programme/10139003/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BDiv', 
        code: '06130008', 
        link: 'https://www.up.ac.za/programmes/programme/06130008/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BDram', 
        code: '01130117', 
        link: 'https://www.up.ac.za/programmes/programme/01130117/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BDram Extended programme', 
        code: '01130118', 
        link: 'https://www.up.ac.za/programmes/programme/01130118/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEd Foundation Phase Teaching', 
        code: '09133011', 
        link: 'https://www.up.ac.za/programmes/programme/09133011/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEd Intermediate Phase Teaching', 
        code: '09133021', 
        link: 'https://www.up.ac.za/programmes/programme/09133021/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEd Senior Phase and Further Education and Training Teaching', 
        code: '09133031', 
        link: 'https://www.up.ac.za/programmes/programme/09133031/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Chemical Engineering', 
        code: '12130002', 
        link: 'https://www.up.ac.za/programmes/programme/12130002/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Chemical Engineering ENGAGE', 
        code: '12136002', 
        link: 'https://www.up.ac.za/programmes/programme/12136002/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Civil Engineering', 
        code: '12130007', 
        link: 'https://www.up.ac.za/programmes/programme/12130007/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Civil Engineering ENGAGE', 
        code: '12136007', 
        link: 'https://www.up.ac.za/programmes/programme/12136007/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Computer Engineering', 
        code: '12130009', 
        link: 'https://www.up.ac.za/programmes/programme/12130009/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Computer Engineering ENGAGE', 
        code: '12136009', 
        link: 'https://www.up.ac.za/programmes/programme/12136009/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Electrical Engineering', 
        code: '12130003', 
        link: 'https://www.up.ac.za/programmes/programme/12130003/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Electrical Engineering ENGAGE', 
        code: '12136003', 
        link: 'https://www.up.ac.za/programmes/programme/12136003/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Electronic Engineering', 
        code: '12130008', 
        link: 'https://www.up.ac.za/programmes/programme/12130008/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Electronic Engineering ENGAGE', 
        code: '12136008', 
        link: 'https://www.up.ac.za/programmes/programme/12136008/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Industrial Engineering', 
        code: '12130001', 
        link: 'https://www.up.ac.za/programmes/programme/12130001/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Industrial Engineering ENGAGE', 
        code: '12136001', 
        link: 'https://www.up.ac.za/programmes/programme/12136001/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Mechanical Engineering', 
        code: '12130004', 
        link: 'https://www.up.ac.za/programmes/programme/12130004/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Mechanical Engineering ENGAGE', 
        code: '12136004', 
        link: 'https://www.up.ac.za/programmes/programme/12136004/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Metallurgical Engineering', 
        code: '12130005', 
        link: 'https://www.up.ac.za/programmes/programme/12130005/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Metallurgical Engineering ENGAGE', 
        code: '12136005', 
        link: 'https://www.up.ac.za/programmes/programme/12136005/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Mining Engineering', 
        code: '12130006', 
        link: 'https://www.up.ac.za/programmes/programme/12130006/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BEng Mining Engineering ENGAGE', 
        code: '12136006', 
        link: 'https://www.up.ac.za/programmes/programme/12136006/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BIS Information Science', 
        code: '12131012', 
        link: 'https://www.up.ac.za/programmes/programme/12131012/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BIS Multimedia', 
        code: '12131013', 
        link: 'https://www.up.ac.za/programmes/programme/12131013/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BIS Publishing', 
        code: '12131014', 
        link: 'https://www.up.ac.za/programmes/programme/12131014/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BIT Information Systems', 
        code: '12133300', 
        link: 'https://www.up.ac.za/programmes/programme/12133300/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BMus', 
        code: '01132003', 
        link: 'https://www.up.ac.za/programmes/programme/01132003/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BMus Extended programme', 
        code: '01132004', 
        link: 'https://www.up.ac.za/programmes/programme/01132004/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BNurs', 
        code: '10131002', 
        link: 'https://www.up.ac.za/programmes/programme/10131002/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BOccTher', 
        code: '10138003', 
        link: 'https://www.up.ac.za/programmes/programme/10138003/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BOH', 
        code: '10132001', 
        link: 'https://www.up.ac.za/programmes/programme/10132001/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BPhysio', 
        code: '10138103', 
        link: 'https://www.up.ac.za/programmes/programme/10138103/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BPolSci International Studies', 
        code: '01130038', 
        link: 'https://www.up.ac.za/programmes/programme/01130038/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BPolSci Political Studies', 
        code: '01130039', 
        link: 'https://www.up.ac.za/programmes/programme/01130039/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BRad in Diagnostics', 
        code: '10137100', 
        link: 'https://www.up.ac.za/programmes/programme/10137100/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Actuarial and Financial Mathematics', 
        code: '02133395', 
        link: 'https://www.up.ac.za/programmes/programme/02133395/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Applied Mathematics', 
        code: '02133253', 
        link: 'https://www.up.ac.za/programmes/programme/02133253/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Architecture', 
        code: '12132018', 
        link: 'https://www.up.ac.za/programmes/programme/12132018/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Biochemistry', 
        code: '02133398', 
        link: 'https://www.up.ac.za/programmes/programme/02133398/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Biological Sciences', 
        code: '02133397', 
        link: 'https://www.up.ac.za/programmes/programme/02133397/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Biotechnology', 
        code: '02133403', 
        link: 'https://www.up.ac.za/programmes/programme/02133403/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Chemistry', 
        code: '02133173', 
        link: 'https://www.up.ac.za/programmes/programme/02133173/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Computer Science', 
        code: '12134001', 
        link: 'https://www.up.ac.za/programmes/programme/12134001/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Construction Management', 
        code: '12132025', 
        link: 'https://www.up.ac.za/programmes/programme/12132025/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Culinary Science', 
        code: '02133320', 
        link: 'https://www.up.ac.za/programmes/programme/02133320/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Ecology', 
        code: '02133400', 
        link: 'https://www.up.ac.za/programmes/programme/02133400/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Engineering and Environmental Geology', 
        code: '02133043', 
        link: 'https://www.up.ac.za/programmes/programme/02133043/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Entomology', 
        code: '02133401', 
        link: 'https://www.up.ac.za/programmes/programme/02133401/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Extended programme - Biological and Agricultural Sciences', 
        code: '02130014', 
        link: 'https://www.up.ac.za/programmes/programme/02130014/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Extended programme - Mathematical Sciences', 
        code: '02130016', 
        link: 'https://www.up.ac.za/programmes/programme/02130016/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Extended programme - Physical Sciences', 
        code: '02130015', 
        link: 'https://www.up.ac.za/programmes/programme/02130015/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Food Science', 
        code: '02133406', 
        link: 'https://www.up.ac.za/programmes/programme/02133406/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Genetics', 
        code: '02133402', 
        link: 'https://www.up.ac.za/programmes/programme/02133402/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Geography and Environmental Science', 
        code: '02133363', 
        link: 'https://www.up.ac.za/programmes/programme/02133363/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Geoinformatics', 
        code: '02133393', 
        link: 'https://www.up.ac.za/programmes/programme/02133393/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Geology', 
        code: '02133023', 
        link: 'https://www.up.ac.za/programmes/programme/02133023/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Human Genetics', 
        code: '02133409', 
        link: 'https://www.up.ac.za/programmes/programme/02133409/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Human Physiology', 
        code: '02133408', 
        link: 'https://www.up.ac.za/programmes/programme/02133408/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Human Physiology, Genetics and Psychology', 
        code: '02133396', 
        link: 'https://www.up.ac.za/programmes/programme/02133396/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Information and Knowledge Systems', 
        code: '12133213', 
        link: 'https://www.up.ac.za/programmes/programme/12133213/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Mathematical Statistics', 
        code: '02133274', 
        link: 'https://www.up.ac.za/programmes/programme/02133274/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Mathematics', 
        code: '02133263', 
        link: 'https://www.up.ac.za/programmes/programme/02133263/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Medical Sciences', 
        code: '02133407', 
        link: 'https://www.up.ac.za/programmes/programme/02133407/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Meteorology', 
        code: '02133313', 
        link: 'https://www.up.ac.za/programmes/programme/02133313/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Microbiology', 
        code: '02133404', 
        link: 'https://www.up.ac.za/programmes/programme/02133404/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Nutrition', 
        code: '02133322', 
        link: 'https://www.up.ac.za/programmes/programme/02133322/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Physics', 
        code: '02133203', 
        link: 'https://www.up.ac.za/programmes/programme/02133203/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Plant Science', 
        code: '02133405', 
        link: 'https://www.up.ac.za/programmes/programme/02133405/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Quantity Surveying', 
        code: '12132023', 
        link: 'https://www.up.ac.za/programmes/programme/12132023/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Real Estate', 
        code: '12132024', 
        link: 'https://www.up.ac.za/programmes/programme/12132024/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSc Zoology', 
        code: '02133399', 
        link: 'https://www.up.ac.za/programmes/programme/02133399/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BScAgric Agricultural Economics and Agribusiness Management', 
        code: '02133410', 
        link: 'https://www.up.ac.za/programmes/programme/02133410/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BScAgric Animal Science', 
        code: '02133411', 
        link: 'https://www.up.ac.za/programmes/programme/02133411/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BScAgric Applied Plant and Soil Sciences', 
        code: '02133431', 
        link: 'https://www.up.ac.za/programmes/programme/02133431/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BScAgric Plant Pathology', 
        code: '02133433', 
        link: 'https://www.up.ac.za/programmes/programme/02133433/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSocSci Heritage and Cultural Tourism', 
        code: '01130068', 
        link: 'https://www.up.ac.za/programmes/programme/01130068/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSocSci Industrial Sociology and Labour Studies', 
        code: '01130064', 
        link: 'https://www.up.ac.za/programmes/programme/01130064/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSocSci Philosophy, Politics and Economics', 
        code: '01130056', 
        link: 'https://www.up.ac.za/programmes/programme/01130056/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSportSci', 
        code: '10135010', 
        link: 'https://www.up.ac.za/programmes/programme/10135010/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BSW', 
        code: '01130144', 
        link: 'https://www.up.ac.za/programmes/programme/01130144/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BTh', 
        code: '06130007', 
        link: 'https://www.up.ac.za/programmes/programme/06130007/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BTRP', 
        code: '12132026', 
        link: 'https://www.up.ac.za/programmes/programme/12132026/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BVetNurs', 
        code: '08130006', 
        link: 'https://www.up.ac.za/programmes/programme/08130006/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'BVSc', 
        code: '08130005', 
        link: 'https://www.up.ac.za/programmes/programme/08130005/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'LLB', 
        code: '04130012', 
        link: 'https://www.up.ac.za/programmes/programme/04130012/year/2023', 
        }, 
        { 
        year: '2023', 
        title: 'MBChB', 
        code: '10130003', 
        link: 'https://www.up.ac.za/programmes/programme/10130003/year/2023', 
        }, 
        
        ],
    },
    {
        id: 4,
        title: 'University of Stellenbosche',
        img: 'https://cdn.24.co.za/files/Cms/General/d/11283/f3f93860f9904f5fa21967a085240dc4.jpg',
        url: 'stellies',
        courses: [],
    },
    {
        id: 5,
        title: 'University of South Africa',
        img: 'https://www.unisa.ac.za/static/corporate_web/Content/UHM/themes/images/17_Unisa_Architecture.jpg',
        url: 'unisa',
        courses: [],
    },
    {
        id: 6,
        title: 'Rhodes University',
        img: 'https://cimages1.touristlink.com/data/cache/RH/OD/ES/OL/DC/A/rhodes-university-_oldcampus_400_300.jpg',
        url: 'rhodes',
        courses: [],
    },
    {
        id: 7,
        title: 'University of johannesburg',
        img: 'https://www.timeshighereducation.com/sites/default/files/institution/header_image/profile_uj_-_header_v20170710.jpg',
        url: 'uj',
        courses: [
            { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Chemistry)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-chemistry/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Chemistry)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Physiology and Psychology)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-physiology-and-psychology/', 
        department: 'BSc in Life and Environmental Sciences (Physiology and Psychology)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Physiology and Psychology) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-physiology-and-psychology-extended/', 
        department: 'BSc in Life and Environmental Sciences (Physiology and Psychology) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Chemistry) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-chemistry-extended/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Chemistry) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Informatics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-informatics-extended/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Informatics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-mathematical-statistics-extended/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Psychology) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-psychology-extended/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Psychology) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Physics and Applied Mathematics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-physics-and-applied-mathematics/', 
        department: 'BSc in Physical Sciences (Physics and Applied Mathematics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Physics and Mathematics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-physics-and-mathematics/', 
        department: 'BSc in Physical Sciences (Physics and Mathematics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Physics and Applied Mathematics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-physics-and-applied-mathematics-extended/', 
        department: 'BSc in Physical Sciences (Physics and Applied Mathematics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Physics and Mathematics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-physics-and-mathematics-extended/', 
        department: 'BSc in Physical Sciences (Physics and Mathematics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-mathematical-statistics-2/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematical Statistics and Computer Science)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematical-statistics-and-computer-science/', 
        department: 'BSc in Mathematical Sciences (Mathematical Statistics and Computer Science)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Actuarial Science)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-actuarial-science/', 
        department: 'BSc in Mathematical Sciences (Actuarial Science)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Geology and Physics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-geology-and-physics/', 
        department: 'BSc in Physical Sciences (Geology and Physics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Applied Mathematics and Mathematics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-applied-mathematics-and-mathematics/', 
        department: 'BSc in Mathematical Sciences (Applied Mathematics and Mathematics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Computational Science)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-computational-science/', 
        department: 'BSc in Mathematical Sciences (Computational Science)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Computer Science)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-computer-science/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Computer Science)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Informatics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-informatics/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Informatics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-mathematical-statistics/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Psychology)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-psychology/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Psychology)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics with Financial Orientation)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-mathematical-statistics-with-financial-orientation/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Mathematical Statistics with Financial Orientation)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematical Statistics and Economics with Financial Orientation)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematical-statistics-and-economics-with-financial-orientation/', 
        department: 'BSc in Mathematical Sciences (Mathematical Statistics and Economics with Financial Orientation)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Economics with Financial Orientation)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-economics-with-financial-orientation/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Economics with Financial Orientation)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Applied Mathematics and Mathematical Statistics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-applied-mathematics-and-mathematical-statistics-extended/', 
        department: 'BSc in Mathematical Sciences (Applied Mathematics and Mathematical Statistics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Applied Mathematics and Mathematics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-applied-mathematics-and-mathematics-extended/', 
        department: 'BSc in Mathematical Sciences (Applied Mathematics and Mathematics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematical Statistics and Computer Science) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematical-statistics-and-computer-science-extended/', 
        department: 'BSc in Mathematical Sciences (Mathematical Statistics and Computer Science) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Sciences (Mathematics and Computer Science) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-sciences-mathematics-and-computer-science-extended/', 
        department: 'BSc in Mathematical Sciences (Mathematics and Computer Science) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Environmental Management)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-environmental-management/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Environmental Management)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Geography)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-geography/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Geography)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Geography and Environmental Management)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-geography-and-environmental-management/', 
        department: 'BSc in Life and Environmental Sciences (Geography and Environmental Management)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Geography and Environmental Management) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-geography-and-environmental-management-extended/', 
        department: 'BSc in Life and Environmental Sciences (Geography and Environmental Management) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Environmental Management) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-environmental-management-extended/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Environmental Management) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Geography) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-geography-extended/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Geography) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Geology and Environmental Management)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-geology-and-environmental-management/', 
        department: 'BSc in Life and Environmental Sciences (Geology and Environmental Management)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Geology and Geography)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-geology-and-geography/', 
        department: 'BSc in Life and Environmental Sciences (Geology and Geography)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Geology and Chemistry)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-geology-and-chemistry/', 
        department: 'BSc in Physical Sciences (Geology and Chemistry)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Geology and Mathematics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-geology-and-mathematics/', 
        department: 'BSc in Physical Sciences (Geology and Mathematics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Botany and Zoology) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-botany-and-zoology-extended/', 
        department: 'BSc in Life and Environmental Sciences (Botany and Zoology) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'Diploma in Analytical Chemistry', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-analytical-chemistry/', 
        department: 'Diploma in Analytical Chemistry', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences(Chemistry and Mathematics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-scienceschemistry-and-mathematics/', 
        department: 'BSc in Physical Sciences(Chemistry and Mathematics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Chemistry and Physics)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-chemistry-and-physics/', 
        department: 'BSc in Physical Sciences (Chemistry and Physics)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Biochemistry and Chemistry) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-biochemistry-and-chemistry-extended/', 
        department: 'BSc in Physical Sciences (Biochemistry and Chemistry) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Chemistry and Mathematics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-chemistry-and-mathematics-extended/', 
        department: 'BSc in Physical Sciences (Chemistry and Mathematics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Sciences (Chemistry and Physics) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-sciences-chemistry-and-physics-extended/', 
        department: 'BSc in Physical Sciences (Chemistry and Physics) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Science (Biochemistry and Botany)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-science-biochemistry-and-botany/', 
        department: 'BSc in Life and Environmental Science (Biochemistry and Botany)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Science (Biochemistry and Zoology)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-science-biochemistry-and-zoology/', 
        department: 'BSc in Life and Environmental Science (Biochemistry and Zoology)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Science (Physiology and Biochemistry)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-science-physiology-and-biochemistry/', 
        department: 'BSc in Life and Environmental Science (Physiology and Biochemistry)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Physical Science (Biochemistry and Chemistry)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-physical-science-biochemistry-and-chemistry/', 
        department: 'BSc in Physical Science (Biochemistry and Chemistry)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Physiology and Biochemistry) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-physiology-and-biochemistry-extended/', 
        department: 'BSc in Life and Environmental Sciences (Physiology and Biochemistry) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Zoology and Biochemistry) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-zoology-and-biochemistry-extended/', 
        department: 'BSc in Life and Environmental Sciences (Zoology and Biochemistry) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'Diploma in Biotechnology', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-biotechnology/', 
        department: 'Diploma in Biotechnology', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'Diploma in Food Technology', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-food-technology/', 
        department: 'Diploma in Food Technology', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Botany and Chemistry)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-botany-and-chemistry/', 
        department: 'BSc in Life and Environmental Sciences (Botany and Chemistry)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Botany and Zoology)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-botany-and-zoology/', 
        department: 'BSc in Life and Environmental Sciences (Botany and Zoology)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Biochemistry and Botany) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-biochemistry-and-botany-extended/', 
        department: 'BSc in Life and Environmental Sciences (Biochemistry and Botany) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Life and Environmental Sciences (Botany and Chemistry) Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-life-and-environmental-sciences-botany-and-chemistry-extended/', 
        department: 'BSc in Life and Environmental Sciences (Botany and Chemistry) Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Science (Applied Mathematics and Computer Science)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-science-applied-mathematics-and-computer-science/', 
        department: 'BSc in Mathematical Science (Applied Mathematics and Computer Science)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Mathematical Science (Applied Mathematics and Computer Science) Exctended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-mathematical-science-applied-mathematics-and-computer-science-exctended/', 
        department: 'BSc in Mathematical Science (Applied Mathematics and Computer Science) Exctended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BCom Law', 
        link: 'https://www.uj.ac.za/university-courses/bcom-law/', 
        department: 'BCom Law', 
        facaulty: 'Faculty of Law', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-law/', 
        }, 
        { 
        title: 'BA Law', 
        link: 'https://www.uj.ac.za/university-courses/ba-law/', 
        department: 'BA Law', 
        facaulty: 'Faculty of Law', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-law/', 
        }, 
        { 
        title: 'BSc in Computer Science and Informatics Specialising in AI (Artificial Intelligence)', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-computer-science-and-informatics-specialising-in-ai-artificial-intelligence/', 
        department: 'BSc in Computer Science and Informatics Specialising in AI (Artificial Intelligence)', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Computer Science and Informatics Extended', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-computer-science-and-informatics-extended/', 
        department: 'BSc in Computer Science and Informatics Extended', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Information Technology', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-information-technology/', 
        department: 'BSc in Information Technology', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BSc in Computer Science and Informatics', 
        link: 'https://www.uj.ac.za/university-courses/bsc-in-computer-science-and-informatics/', 
        department: 'BSc in Computer Science and Informatics', 
        facaulty: 'Faculty of Science', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-science/', 
        }, 
        { 
        title: 'BA in Language Practice', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-language-practice/', 
        department: 'BA in Language Practice', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'BA with specialisation in Language Practice', 
        link: 'https://www.uj.ac.za/university-courses/ba-with-specialisation-in-language-practice/', 
        department: 'BA with specialisation in Language Practice', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'BA with specialisation in Development Studies Extended', 
        link: 'https://www.uj.ac.za/university-courses/ba-with-specialisation-in-development-studies-extended/', 
        department: 'BA with specialisation in Development Studies Extended', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'BA with specialisation in Linguistics Extended', 
        link: 'https://www.uj.ac.za/university-courses/ba-with-specialisation-in-linguistics-extended/', 
        department: 'BA with specialisation in Linguistics Extended', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'BA with specialisation in Linguistics and Language Practice Extended', 
        link: 'https://www.uj.ac.za/university-courses/ba-with-specialisation-in-linguistics-and-language-practice-extended/', 
        department: 'BA with specialisation in Linguistics and Language Practice Extended', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'BA with specialisation in Strategic Communication Extended', 
        link: 'https://www.uj.ac.za/university-courses/ba-with-specialisation-in-strategic-communication-extended/', 
        department: 'BA with specialisation in Strategic Communication Extended', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'LLB in Law', 
        link: 'https://www.uj.ac.za/university-courses/llb-in-law/', 
        department: 'LLB in Law', 
        facaulty: 'Faculty of Law', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-law/', 
        }, 
        { 
        title: 'Bachelor of Social Work', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-social-work/', 
        department: 'Bachelor of Social Work', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'Diploma in Public Relations and Communication', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-public-relations-and-communication/', 
        department: 'Diploma in Public Relations and Communication', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'Diploma in Public Relations and Communication Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-public-relations-and-communication-extended/', 
        department: 'Diploma in Public Relations and Communication Extended', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'BA in Community Development and Leadership', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-community-development-and-leadership/', 
        department: 'BA in Community Development and Leadership', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'Bachelor of Arts', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-arts/', 
        department: 'Bachelor of Arts', 
        facaulty: 'Faculty of Humanities', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-humanities/', 
        }, 
        { 
        title: 'Bachelor of Optometry', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-optometry/', 
        department: 'Bachelor of Optometry', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Health Sciences in Podiatry', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-health-sciences-in-podiatry/', 
        department: 'Bachelor of Health Sciences in Podiatry', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Higher Certificate in Sport Administration', 
        link: 'https://www.uj.ac.za/university-courses/higher-certificate-in-sport-administration/', 
        department: 'Higher Certificate in Sport Administration', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Higher Certificate Sport Coaching and Exercise Sciences', 
        link: 'https://www.uj.ac.za/university-courses/higher-certificate-sport-coaching-and-exercise-sciences/', 
        department: 'Higher Certificate Sport Coaching and Exercise Sciences', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Diploma in Sport Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-sport-management/', 
        department: 'Diploma in Sport Management', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Commerce in Sport Management', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-commerce-in-sport-management/', 
        department: 'Bachelor of Commerce in Sport Management', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Health Sciences in Sport and Exercise Sciences', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-health-sciences-in-sport-and-exercise-sciences/', 
        department: 'Bachelor of Health Sciences in Sport and Exercise Sciences', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Biokinetics', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-biokinetics/', 
        department: 'Bachelor of Biokinetics', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor Diagnostic Radiography', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-diagnostic-radiography/', 
        department: 'Bachelor Diagnostic Radiography', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Diagnostic Ultrasound', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-diagnostic-ultrasound/', 
        department: 'Bachelor of Diagnostic Ultrasound', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Nuclear Medicine', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-nuclear-medicine/', 
        department: 'Bachelor of Nuclear Medicine', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Radiation Therapy', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-radiation-therapy/', 
        department: 'Bachelor of Radiation Therapy', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Nursing', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-nursing/', 
        department: 'Bachelor of Nursing', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Higher Certificate in Emergency Medical Care', 
        link: 'https://www.uj.ac.za/university-courses/higher-certificate-in-emergency-medical-care/', 
        department: 'Higher Certificate in Emergency Medical Care', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Diploma in Emergency Medical Care', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-emergency-medical-care/', 
        department: 'Diploma in Emergency Medical Care', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Health Sciences in Emergency Medical Care', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-health-sciences-in-emergency-medical-care/', 
        department: 'Bachelor of Health Sciences in Emergency Medical Care', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Environmental Health', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-environmental-health/', 
        department: 'Bachelor of Environmental Health', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Health Sciences in Chiropractic', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-health-sciences-in-chiropractic/', 
        department: 'Bachelor of Health Sciences in Chiropractic', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Health Sciences in Complementary Medicine', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-health-sciences-in-complementary-medicine/', 
        department: 'Bachelor of Health Sciences in Complementary Medicine', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Bachelor of Urban and Regional Planning', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-urban-and-regional-planning/', 
        department: 'Bachelor of Urban and Regional Planning', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Bachelor of Health Sciences in Medical Laboratory Sciences', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-health-sciences-in-medical-laboratory-sciences/', 
        department: 'Bachelor of Health Sciences in Medical Laboratory Sciences', 
        facaulty: 'Faculty of Health Sciences', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-health-sciences/', 
        }, 
        { 
        title: 'Diploma in Operations Management Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-operations-management-extended/', 
        department: 'Diploma in Operations Management Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Extraction Metallurgy', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-extraction-metallurgy/', 
        department: 'BEng Tech in Extraction Metallurgy', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Physical Metallurgy', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-physical-metallurgy/', 
        department: 'BEng Tech in Physical Metallurgy', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Extraction Metallurgy Extended', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-extraction-metallurgy-extended/', 
        department: 'BEng Tech in Extraction Metallurgy Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Physical Metallurgy Extended', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-physical-metallurgy-extended/', 
        department: 'BEng Tech in Physical Metallurgy Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Mining Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-mining-engineering/', 
        department: 'BEng Tech in Mining Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Bachelor of Mine Surveying', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-mine-surveying/', 
        department: 'Bachelor of Mine Surveying', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Diploma in Management Services', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-management-services/', 
        department: 'Diploma in Management Services', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Diploma in Operations Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-operations-management/', 
        department: 'Diploma in Operations Management', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Diploma in Management Services Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-management-services-extended/', 
        department: 'Diploma in Management Services Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng in Electrical and Electronic Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-in-electrical-and-electronic-engineering/', 
        department: 'BEng in Electrical and Electronic Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Electrical Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-electrical-engineering/', 
        department: 'BEng Tech in Electrical Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Electrical Engineering Extended', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-electrical-engineering-extended/', 
        department: 'BEng Tech in Electrical Engineering Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Industrial Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-industrial-engineering/', 
        department: 'BEng Tech in Industrial Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Mechanical Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-mechanical-engineering/', 
        department: 'BEng Tech in Mechanical Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Industrial Engineering Extended', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-industrial-engineering-extended/', 
        department: 'BEng Tech in Industrial Engineering Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Mechanical Engineering Extended', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-mechanical-engineering-extended/', 
        department: 'BEng Tech in Mechanical Engineering Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng in Mechanical Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-in-mechanical-engineering/', 
        department: 'BEng in Mechanical Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng in Civil Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-in-civil-engineering/', 
        department: 'BEng in Civil Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Civil Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-civil-engineering/', 
        department: 'BEng Tech in Civil Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Civil Engineering Extended', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-civil-engineering-extended/', 
        department: 'BEng Tech in Civil Engineering Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Bachelor of Science in Construction Extended', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-science-in-construction-extended/', 
        department: 'Bachelor of Science in Construction Extended', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'Bachelor of Science in Construction', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-science-in-construction/', 
        department: 'Bachelor of Science in Construction', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BEng Tech in Chemical Engineering', 
        link: 'https://www.uj.ac.za/university-courses/beng-tech-in-chemical-engineering/', 
        department: 'BEng Tech in Chemical Engineering', 
        facaulty: 'Faculty of Engineering and the Built Environment', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-engineering-and-the-built-environment/', 
        }, 
        { 
        title: 'BA in Interior Design', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-interior-design/', 
        department: 'BA in Interior Design', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'Diploma in Jewellery Design and Manufacture', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-jewellery-design-and-manufacture/', 
        department: 'Diploma in Jewellery Design and Manufacture', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BA in Digital Media Design', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-digital-media-design/', 
        department: 'BA in Digital Media Design', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BA in Visual Art', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-visual-art/', 
        department: 'BA in Visual Art', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BEd in Senior Phase and FET Teaching (Geography)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-senior-phase-and-fet-teaching-geography/', 
        department: 'BEd in Senior Phase and FET Teaching (Geography)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'Diploma in Architecture', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-architecture/', 
        department: 'Diploma in Architecture', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'Bachelor of Architecture', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-architecture/', 
        department: 'Bachelor of Architecture', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'Diploma in Fashion Production', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-fashion-production/', 
        department: 'Diploma in Fashion Production', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BA in Fashion Design', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-fashion-design/', 
        department: 'BA in Fashion Design', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BA in Design in Communication Design', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-design-in-communication-design/', 
        department: 'BA in Design in Communication Design', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BA in Industrial Design', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-industrial-design/', 
        department: 'BA in Industrial Design', 
        facaulty: 'Faculty of Art, Design and Architecture', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-art-design-and-architecture/', 
        }, 
        { 
        title: 'BEd in Senior Phase and FET Teaching (Psychology or Life Orientation)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-senior-phase-and-fet-teaching-psychology-or-life-orientation/', 
        department: 'BEd in Senior Phase and FET Teaching (Psychology or Life Orientation)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd in Senior Phase and FET Teaching (Mathematics)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-senior-phase-and-fet-teaching-mathematics/', 
        department: 'BEd in Senior Phase and FET Teaching (Mathematics)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd in Senior Phase and FET Teaching (Physical Science)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-senior-phase-and-fet-teaching-physical-science/', 
        department: 'BEd in Senior Phase and FET Teaching (Physical Science)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd in Senior Phase and FET Teaching (Life Sciences)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-senior-phase-and-fet-teaching-life-sciences/', 
        department: 'BEd in Senior Phase and FET Teaching (Life Sciences)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd Senior and FET Phase Teaching (Accounting)', 
        link: 'https://www.uj.ac.za/university-courses/bed-senior-and-fet-phase-teaching-accounting/', 
        department: 'BEd Senior and FET Phase Teaching (Accounting)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd Senior and FET Phase Teaching (Business Management)', 
        link: 'https://www.uj.ac.za/university-courses/bed-senior-and-fet-phase-teaching-business-management/', 
        department: 'BEd Senior and FET Phase Teaching (Business Management)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd Senior and FET Phase Teaching (Economics)', 
        link: 'https://www.uj.ac.za/university-courses/bed-senior-and-fet-phase-teaching-economics/', 
        department: 'BEd Senior and FET Phase Teaching (Economics)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd Senior and FET Phase Teaching (English)', 
        link: 'https://www.uj.ac.za/university-courses/bed-senior-and-fet-phase-teaching-english/', 
        department: 'BEd Senior and FET Phase Teaching (English)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd Senior and FET Phase Teaching (Afrikaans)', 
        link: 'https://www.uj.ac.za/university-courses/bed-senior-and-fet-phase-teaching-afrikaans/', 
        department: 'BEd Senior and FET Phase Teaching (Afrikaans)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd Senior and FET Phase Teaching (Sepedi)', 
        link: 'https://www.uj.ac.za/university-courses/bed-senior-and-fet-phase-teaching-sepedi/', 
        department: 'BEd Senior and FET Phase Teaching (Sepedi)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd in Senior Phase and FET Teaching (Isizulu)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-senior-phase-and-fet-teaching-isizulu/', 
        department: 'BEd in Senior Phase and FET Teaching (Isizulu)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd in Foundation Phase Teaching (Grade R-3)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-foundation-phase-teaching-grade-r-3/', 
        department: 'BEd in Foundation Phase Teaching (Grade R-3)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'BEd in Intermediate Phase Teaching (Grade 4-7)', 
        link: 'https://www.uj.ac.za/university-courses/bed-in-intermediate-phase-teaching-grade-4-7/', 
        department: 'BEd in Intermediate Phase Teaching (Grade 4-7)', 
        facaulty: 'Faculty of Education', 
        faclink: 'https://www.uj.ac.za/faculty/faculty-of-education/', 
        }, 
        { 
        title: 'Bachelor of Tourism Development and Management', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-tourism-development-and-management/', 
        department: 'Bachelor of Tourism Development and Management', 
        facaulty: 'Department of Tourism Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-tourism-management/', 
        }, 
        { 
        title: 'Diploma in Tourism Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-tourism-management/', 
        department: 'Diploma in Tourism Management', 
        facaulty: 'Department of Tourism Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-tourism-management/', 
        }, 
        { 
        title: 'BCom in Transport and Logistics Management', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-transport-and-logistics-management/', 
        department: 'BCom in Transport and Logistics Management', 
        facaulty: 'Department of Transport and Supply Chain Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-transport-and-supply-chain-management/', 
        }, 
        { 
        title: 'Diploma in Logistics', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-logistics/', 
        department: 'Diploma in Logistics', 
        facaulty: 'Department of Transport and Supply Chain Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-transport-and-supply-chain-management/', 
        }, 
        { 
        title: 'Diploma in Transportation Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-transportation-management/', 
        department: 'Diploma in Transportation Management', 
        facaulty: 'Department of Transport and Supply Chain Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-transport-and-supply-chain-management/', 
        }, 
        { 
        title: 'Diploma in Logistics Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-logistics-extended/', 
        department: 'Diploma in Logistics Extended', 
        facaulty: 'Department of Transport and Supply Chain Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-transport-and-supply-chain-management/', 
        }, 
        { 
        title: 'Diploma in Transportation Management Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-transportation-management-extended/', 
        department: 'Diploma in Transportation Management Extended', 
        facaulty: 'Department of Transport and Supply Chain Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-transport-and-supply-chain-management/', 
        }, 
        { 
        title: 'BA in Public Management and Governance', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-public-management-and-governance/', 
        department: 'BA in Public Management and Governance', 
        facaulty: 'Department of Public Management and Governance', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-public-management-and-governance/', 
        }, 
        { 
        title: 'BA in Public Management and Governance', 
        link: 'https://www.uj.ac.za/university-courses/ba-in-public-management-and-governance-2/', 
        department: 'BA in Public Management and Governance', 
        facaulty: 'Department of Public Management and Governance', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-public-management-and-governance/', 
        }, 
        { 
        title: 'BCom in Information Management', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-information-management/', 
        department: 'BCom in Information Management', 
        facaulty: 'Department of Information and Knowledge Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-information-and-knowledge-management/', 
        }, 
        { 
        title: 'BCom in Marketing Management', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-marketing-management/', 
        department: 'BCom in Marketing Management', 
        facaulty: 'Department of Marketing Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-marketing-management/', 
        }, 
        { 
        title: 'Diploma in Marketing', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-marketing/', 
        department: 'Diploma in Marketing', 
        facaulty: 'Department of Marketing Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-marketing-management/', 
        }, 
        { 
        title: 'Diploma in Retail Business Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-retail-business-management/', 
        department: 'Diploma in Retail Business Management', 
        facaulty: 'Department of Marketing Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-marketing-management/', 
        }, 
        { 
        title: 'Diploma in People Management Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-people-management-extended/', 
        department: 'Diploma in People Management Extended', 
        facaulty: 'Department of Industrial Psychology and People Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-industrial-psychology-and-people-management/', 
        }, 
        { 
        title: 'Bachelor of Human Resource Management', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-human-resource-management/', 
        department: 'Bachelor of Human Resource Management', 
        facaulty: 'Department of Industrial Psychology and People Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-industrial-psychology-and-people-management/', 
        }, 
        { 
        title: 'BCom in Industrial Psychology', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-industrial-psychology/', 
        department: 'BCom in Industrial Psychology', 
        facaulty: 'Department of Industrial Psychology and People Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-industrial-psychology-and-people-management/', 
        }, 
        { 
        title: 'Diploma in People Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-people-management/', 
        department: 'Diploma in People Management', 
        facaulty: 'Department of Industrial Psychology and People Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-industrial-psychology-and-people-management/', 
        }, 
        { 
        title: 'BCom in Finance', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-finance/', 
        department: 'BCom in Finance', 
        facaulty: 'Department of Finance and Investment Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-finance-and-investment-management/', 
        }, 
        { 
        title: 'BCom in Finance Extended', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-finance-extended/', 
        department: 'BCom in Finance Extended', 
        facaulty: 'Department of Finance and Investment Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-finance-and-investment-management/', 
        }, 
        { 
        title: 'Diploma in Financial Services Operations', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-financial-services-operations/', 
        department: 'Diploma in Financial Services Operations', 
        facaulty: 'Department of Finance and Investment Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-finance-and-investment-management/', 
        }, 
        { 
        title: 'Bachelor of Hospitality Management', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-hospitality-management/', 
        department: 'Bachelor of Hospitality Management', 
        facaulty: 'Department of Hospitality Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-hospitality-management/', 
        }, 
        { 
        title: 'Diploma in Food and Beverage Operations', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-food-and-beverage-operations/', 
        department: 'Diploma in Food and Beverage Operations', 
        facaulty: 'Department of Hospitality Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-hospitality-management/', 
        }, 
        { 
        title: 'BCom in Economics and Econometrics', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-economics-and-econometrics/', 
        department: 'BCom in Economics and Econometrics', 
        facaulty: 'Department of Economics and Econometrics', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-economics-and-econometrics/', 
        }, 
        { 
        title: 'BCom in Economics and Econometrics Extended', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-economics-and-econometrics-extended/', 
        department: 'BCom in Economics and Econometrics Extended', 
        facaulty: 'Department of Economics and Econometrics', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-economics-and-econometrics/', 
        }, 
        { 
        title: 'BCom in Business Management', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-business-management/', 
        department: 'BCom in Business Management', 
        facaulty: 'Department of Business Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-business-management/', 
        }, 
        { 
        title: 'BCom in Entrepreneurial Management', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-entrepreneurial-management/', 
        department: 'BCom in Entrepreneurial Management', 
        facaulty: 'Department of Business Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-business-management/', 
        }, 
        { 
        title: 'BCom in Business Management Extended', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-business-management-extended/', 
        department: 'BCom in Business Management Extended', 
        facaulty: 'Department of Business Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-business-management/', 
        }, 
        { 
        title: 'Diploma in Small Business Management', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-small-business-management/', 
        department: 'Diploma in Small Business Management', 
        facaulty: 'Department of Business Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-business-management/', 
        }, 
        { 
        title: 'Diploma in Small Business Management Extended', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-small-business-management-extended/', 
        department: 'Diploma in Small Business Management Extended', 
        facaulty: 'Department of Business Management', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-business-management/', 
        }, 
        { 
        title: 'Diploma in Accountancy', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-accountancy/', 
        department: 'Diploma in Accountancy', 
        facaulty: 'Department of Commercial Accounting', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-commercial-accounting/', 
        }, 
        { 
        title: 'BCom in Information Systems', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-information-systems/', 
        department: 'BCom in Information Systems', 
        facaulty: 'Department of Applied Information Systems', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-applied-information-systems/', 
        }, 
        { 
        title: 'Diploma in Business Information Technology', 
        link: 'https://www.uj.ac.za/university-courses/diploma-in-business-information-technology/', 
        department: 'Diploma in Business Information Technology', 
        facaulty: 'Department of Applied Information Systems', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-applied-information-systems/', 
        }, 
        { 
        title: 'BCom in Accounting Extended', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-accounting-extended/', 
        department: 'BCom in Accounting Extended', 
        facaulty: 'Department of Accountancy', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-accountancy/', 
        }, 
        { 
        title: 'Bachelor of Accounting (CA-stream)', 
        link: 'https://www.uj.ac.za/university-courses/bachelor-of-accounting-ca-stream/', 
        department: 'Bachelor of Accounting (CA-stream)', 
        facaulty: 'Department of Accountancy', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-accountancy/', 
        }, 
        { 
        title: 'BCom in Accounting', 
        link: 'https://www.uj.ac.za/university-courses/bcom-in-accounting/', 
        department: 'BCom in Accounting', 
        facaulty: 'Department of Accountancy', 
        faclink: 'https://www.uj.ac.za/faculty/college-of-business-and-economics/department-of-accountancy/', 
        }, 
        ],
    },
    
];
